project_id = "jhkxcplfempenoczcoep"

[functions.send-complaint-email]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.chatbot-admin]
verify_jwt = false

[functions.chatbot-public]
verify_jwt = false