// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhkxcplfempenoczcoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impoa3hjcGxmZW1wZW5vY3pjb2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQxNTcsImV4cCI6MjA2NTU4MDE1N30.WQgbaSWF6PebXLDX5PUWuP4dM-vsyBimcv3lMxhVJ30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});